### ISSUE TITLE
I get this error after scraping about 800 records

### ISSUE THREAD

**Issue by rrcreativesolutions** [mez0cc/linky#13]
Traceback (most recent call last):
  File "linky.py", line 147, in <module>
    users=core.run(data)
  File "C:\Users\Clint\Downloads\Linkedin scraper\lib\core.py", line 63, in run
    logger.dump(users,validation)
  File "C:\Users\Clint\Downloads\Linkedin scraper\lib\logger.py", line 211, in dump
    green('%s (%s): %s at %s' % (GREEN(fullname),email,current_role,GREEN(current_company)))
  File "C:\Users\Clint\Downloads\Linkedin scraper\lib\logger.py", line 57, in green
    print('['+log_time+']'+GREEN(' >> ' )+string)
  File "C:\Users\Clint\DOWNLO~1\LINKED~1\env\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 108-109: character maps to <undefined>

**Comment by mez0cc** [comment]
Not too sure whats happening here. Could you elaborate on the issue?
